In [5]:
import sys
sys.path.append("/Users/stevehuang/venv/lib/python3.11/site-packages")
import numpy as np

a = np.array([7, 5, 6])
#b = np.array([1, 77, 2, 3])
print(a)
#print(b[2])

[7 5 6]


In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

a[1][0] = 6
a[2][1] = 8
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [6 4]
 [5 8]]


In [11]:
#print(a[1][2])

In [26]:
import sys
sys.path.append("/Users/stevehuang/venv/lib/python3.11/site-packages")
import numpy as np

a = np.full((7, 3), 3)
print(a)

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
a = np.zeros((4, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
import sys
sys.path.append("/Users/stevehuang/venv/lib/python3.11/site-packages")
import numpy as np

a = np.empty((7, 6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
b=  np.random.random((2 ,3))
print(b)


[[0.16130988 0.89736531 0.49665554]
 [0.64972949 0.45886122 0.21724161]]


In [ ]:
a = np.arange(10, 50, 5)
print(a)

[10 15 20 25 30 35 40 45]


In [ ]:
print(a)
#%%
a = np.arange(10, 50, 5)
b = a.copy()
print(a)
print(b)

c = a + b
print(c)
print(a + 2)

[10 15 20 25 30 35 40 45]
[10 15 20 25 30 35 40 45]
[10 15 20 25 30 35 40 45]
[20 30 40 50 60 70 80 90]
[12 17 22 27 32 37 42 47]


In [ ]:
a = np.full((3, 4), 5)
print(a)
b = np.full((3, 4), 7)
print(b)
c = np.concatenate((a, b), axis=0)
print(f"concatenate:\n {c}")
d = np.vstack((a, b))
print(f"vstack:\n {d}")
d = np.hstack((a, b))
print(f"hstack:\n {d}")
d = np.stack((a, b))
print(f"stack:\n {d}")
d = np.reshape(d, (6, 4))
print(f"reshaped:\n{d}")
print(f"flattened:{0}\n", d.flatten())
print(f"ravel:{0}\n", d.ravel())

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
concatenate:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
vstack:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
hstack:
 [[5 5 5 5 7 7 7 7]
 [5 5 5 5 7 7 7 7]
 [5 5 5 5 7 7 7 7]]
stack:
 [[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]
reshaped:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
flattened:0
 [5 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7 7 7 7]
ravel:0
 [5 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7 7 7 7]


In [ ]:
d = np.linspace(10, 100, 12)
dResh = d.reshape((3, 4))

print(d)
print(dResh)
print(np.mean(dResh, axis=0))
print(np.std(dResh, axis=0))
print(f"sub{0}", dResh - np.mean(dResh, axis=0))

[ 10.          18.18181818  26.36363636  34.54545455  42.72727273
  50.90909091  59.09090909  67.27272727  75.45454545  83.63636364
  91.81818182 100.        ]
[[ 10.          18.18181818  26.36363636  34.54545455]
 [ 42.72727273  50.90909091  59.09090909  67.27272727]
 [ 75.45454545  83.63636364  91.81818182 100.        ]]
[42.72727273 50.90909091 59.09090909 67.27272727]
[26.72170628 26.72170628 26.72170628 26.72170628]
sub0 [[-3.27272727e+01 -3.27272727e+01 -3.27272727e+01 -3.27272727e+01]
 [ 0.00000000e+00 -7.10542736e-15  7.10542736e-15  1.42108547e-14]
 [ 3.27272727e+01  3.27272727e+01  3.27272727e+01  3.27272727e+01]]
